### ISSUE TITLE
Quotes as per 29.01.2014

### ISSUE THREAD

**Issue by AnkeSR** [klokantech/bmarchives-tickets#36]
Please send us the quotes as discussed in our meeting in November 2013

**Comment by klokan** [comment]
I am sorry for the delay. We were discussing a rather large quote document with alternatives and several options for next three big stages of the upgrade of the BMArchives system (Omeka2+design upgrade, new digital archiving system, automated updates of digital archive and automated billing system).

If you need only non-binding rough estimates instead it can be provided quite fast. Otherwise I still have to run some more tests, before a proper quote can be provided.

**Comment by AnkeSR** [comment]
I just wanted to follow up on the quote. Have you been able to establish anything regarding the next stages of the upgrade? Perhaps you could contact Guy and have a chat with him to explain.

**Comment by klokan** [comment]
Provided. Closing.
